#!groovy
//1、定义参数
def shareLibrary = 'deploy-library-dev'
def appName = 'service-message'

//2、引入jenkins定义好的全局共享库
library "${shareLibrary}"

//3、构建参数并调用共享库中部署脚本
def map = [:]
map.put('appName', appName)
buildJob(map)