metadata:
- appName: ''
  dataId: db.properties
  desc: 数据库公用配置
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: dubbo.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: redis.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: activemq.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: fastdfs.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: rocketmq.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-user.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: web-portal-api.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-timer.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-sequence.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-merchant.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-message.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-mch-notify.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-base-config.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-sharding-db.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-rocketmq.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-timer.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-sequence.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-fastdfs.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: web-pms.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-extend.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-arthas.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: gateway-api.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: rabbitmq.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-rabbitmq.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-activemq.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: log4j2.xml
  desc: ''
  group: DEFAULT_GROUP
  type: xml
- appName: ''
  dataId: demo-logging.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: sentinel-rules.properties
  desc: sentinel相关流控、熔断等规则的配置文件
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: sentinel-dashboard.properties
  desc: sentinel控制台的配置文件
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: sentinel-token-client.properties
  desc: sentinel集群流控的客户端配置
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: redis-lock.properties
  desc: redis分布式锁的配置
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-gateway-backend-flux.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-gateway-backend-mvc.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-gateway-backend-nosentinel.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-redis-single.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: redis-multi.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-redis-multi.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: redis-limiter.properties
  desc: redis限流器配置
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: minio.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-minio.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-account-mch.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-dubbo-provider.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-dubbo-consumer.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: elasticsearch.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-elasticsearch.properties
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: gateway-callback.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-gateway-backend-callback.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: demo-oss.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: oss.properties
  group: DEFAULT_GROUP
  type: properties
