apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: service-sequence
    team: payment
  name: service-sequence
  namespace: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-sequence
  serviceName: service
  template:
    metadata:
      labels:
        app: service-sequence
        team: payment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - service-sequence
              topologyKey: kubernetes.io/hostname
            weight: 100
      imagePullSecrets:
       - name: <REG_SECRET_NAME>
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        image: <IMAGE_NAME>
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "0.5"
            memory: 512M
        volumeMounts:
        - mountPath: /home/payment/logs
          name: log-volume
          subPathExpr: $(POD_NAME)
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/xpay/logs
          type: DirectoryOrCreate
        name: log-volume