apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-portal-view
    team: payment
  name: web-portal-view
  namespace: payment-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-portal-view
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-portal-view
        team: payment
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web-portal-view
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: <REG_SECRET_NAME>
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app']
          image: <IMAGE_NAME>
          imagePullPolicy: IfNotPresent
          name: app
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 512M
          volumeMounts:
            - mountPath: /home/payment/logs
              name: log-volume
              subPathExpr: $(POD_NAME)
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/xpay/logs
            type: DirectoryOrCreate
          name: log-volume